###
### GET locale
GET http://localhost:5000/Meteo

###
### POST locale
POST http://localhost:5000/Meteo HTTP/1.1
content-type: application/json

{
    "temperatura": 16,
    "previsione": "Fresco"
}

###
### POST locale (solo temperatura)
POST http://localhost:5000/Meteo HTTP/1.1
content-type: application/json

{
    "temperatura": 22
}

###
### DELETE locale
DELETE http://localhost:5000/Meteo HTTP/1.1

###
### DELETE(ID) locale
DELETE http://localhost:5000/Meteo/3 HTTP/1.1


###################################
### Azure!!!

###
### GET su Azure
GET https://enumweb.azurewebsites.net/Meteo

###
### POST su Azure
POST https://enumweb.azurewebsites.net/Meteo HTTP/1.1
content-type: application/json

{
    "temperatura": 16,
    "previsione": "Fresco"
}

###
### POST su Azure (solo temperatura)
POST https://enumweb.azurewebsites.net/Meteo HTTP/1.1
content-type: application/json

{
    "temperatura": 22
}

###
### DELETE su Azure
DELETE https://enumweb.azurewebsites.net/Meteo HTTP/1.1

###
### DELETE(ID) su Azure
DELETE https://enumweb.azurewebsites.net/Meteo/3 HTTP/1.1

GET https://enumweb.azurewebsites.net/Meteo HTTP/1.1
Accept: application/json